train:
  _target_: data_loader.ImageDataLoader
  data_dir: "data/waste_dataset"
  batch_size: 32
  num_workers: 4
  shuffle: True
  validation_split: 0.2
  random_seed: 0
  use_weighted_sampler: True
test:
  _target_: data_loader.ImageDataLoader
  data_dir: "data/waste_dataset"
  batch_size: 256
  num_workers: 4
